# fly.toml app configuration file generated for 2playerwordle-solitary-hill-4144 on 2024-03-31T00:09:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2playerwordle-solitary-hill-4144'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
